/* NON KEY */

SELECT ACC_NAME,DEAL_DATE FROM ACCOUNT
NATURAL JOIN DEAL
HAVING EXTRACT(MONTH FROM DEAL_DATE)=4
GROUP BY(ACC_NAME,DEAL_DATE);

SELECT ACC_NAME,DEAL_DATE FROM ACCOUNT
NATURAL JOIN DEAL
WHERE DEAL_DATE LIKE '29-02%';

SELECT ACC_NAME,ACC_PHONE,DEAL_STATUS FROM ACCOUNT
NATURAL JOIN DEAL
WHERE ACC_PHONE LIKE '0822%' AND DEAL_STATUS='Lunas';

/* KEY */
SELECT PROD_ID,PROD_TITLE,COUNT(DEAL_STATUS) AS "JUMLAH TIDAK LUNAS" FROM PRODUCT
NATURAL JOIN DEAL
WHERE PROD_ID='4734' AND DEAL_STATUS='Tidak Lunas'
GROUP BY(PROD_ID,PROD_TITLE);

SELECT PROD_ID,DEAL_DATE FROM PRODUCT
NATURAL JOIN DEAL
WHERE PROD_ID='4734';

