CREATE TABLE ACCOUNT (
    ACC_ID NUMBER NOT NULL,
    ACC_NAME VARCHAR2(50) NOT NULL,
    ACC_PHONE VARCHAR2(12) NOT NULL,
    ACC_PASSWORD VARCHAR2(12) NOT NULL,
    CONSTRAINT ACC_PK PRIMARY KEY(ACC_ID) ENABLE,
    CONSTRAINT ACC_UNIQUE UNIQUE(ACC_PHONE)
);

CREATE TABLE PRODUCT (
    PROD_ID NUMBER NOT NULL,
    PROD_TITLE VARCHAR2(100) NOT NULL,
    PROD_PRICE NUMBER NOT NULL,
    CONSTRAINT PROD_PK PRIMARY KEY(PROD_ID) ENABLE
);

CREATE TABLE DEAL (
    DEAL_ID VARCHAR2(30) NOT NULL,
    ACC_ID NUMBER NOT NULL,
    PROD_ID NUMBER NOT NULL,
    DEAL_DATE DATE,
    DEAL_STATUS VARCHAR2(11) DEFAULT 'TIDAK LUNAS' NOT NULL,
    CONSTRAINT DEAL_PK PRIMARY KEY(DEAL_ID) ENABLE,
    CONSTRAINT DEAL_FK1 FOREIGN KEY(ACC_ID) REFERENCES ACCOUNT(ACC_ID) ENABLE,
    CONSTRAINT DEAL_FK2 FOREIGN KEY(PROD_ID) REFERENCES PRODUCT(PROD_ID) ENABLE
);